# This workflow runs all Python-related checks and tests with the latest versions of all development tools.

name: edge tests

on:
  schedule:
    - cron:  '40 20 1 * *'

env:
    MEMCACHED: localhost:11211
    SPARK_VERSION: "23.0"
    GNAT_VERSION: "23.0w-20220723"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - black
          - isort
          - flake8
          - pylint
          - mypy
          - pydocstyle
          - contracts
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install GNAT Pro
      uses: ./.github/actions/install_gnat_pro
      with:
        version: ${{ env.GNAT_VERSION }}
        ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
        server: ${{ secrets.MEMCACHED_SERVER }}
    - name: Install SPARK Pro
      uses: ./.github/actions/install_spark_pro
      with:
        version: ${{ env.SPARK_VERSION }}
        ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
        server: ${{ secrets.MEMCACHED_SERVER }}
    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        sudo apt install libgmp-dev patchelf
        python -m pip install --upgrade pip wheel
        make init install_devel_edge
    - name: Check
      run: |
        make check_${{ matrix.target }}

  tests_python:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - "python"
          - "python_property"
          - "python_optimized"
          - "python_coverage"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install GNAT Pro
      uses: ./.github/actions/install_gnat_pro
      with:
        version: ${{ env.GNAT_VERSION }}
        ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
        server: ${{ secrets.MEMCACHED_SERVER }}
    - name: Install SPARK Pro
      uses: ./.github/actions/install_spark_pro
      with:
        version: ${{ env.SPARK_VERSION }}
        ssh_key: ${{ secrets.MEMCACHED_SSH_KEY }}
        server: ${{ secrets.MEMCACHED_SERVER }}
    - name: Install dependencies
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "HYPOTHESIS_PROFILE=ci" >> $GITHUB_ENV
        echo "PYTEST_ADDOPTS=--basetemp=build" >> $GITHUB_ENV
        sudo apt install graphviz libgmp-dev patchelf
        python -m pip install --upgrade pip wheel
        make init install_devel_edge
    - name: Configure kernel parameters
      run: |
        sudo /sbin/sysctl -w net.ipv4.ping_group_range="0 2147483647"
    - name: Test
      run: |
        make test_${{ matrix.target }}
